apiVersion: 1

prune: false

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: grafana_loki
    url: $LOKI_INTERNAL_URL
    isDefault: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: '${__value.raw}'
          datasourceUid: grafana_tempo

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: $PROMETHEUS_INTERNAL_URL
    isDefault: false

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: $TEMPO_INTERNAL_URL
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: grafana_loki
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
      serviceMap:
        datasourceUid: grafana_prometheus
      nodeGraph:
        enabled: true
